### PR TITLE
Mapkit routes

### PR DESCRIPTION
**Pull request by BQZic**
Add a function to convert hex string into UIColor

### CODE REVIEW

**Review by quuu — CHANGES_REQUESTED** [review]
Like the changes,

Need to resolve merge conflicts,

Slight file differences

**Comment by BQZic** [comment]
> Like the changes,
> 
> Need to resolve merge conflicts,
> 
> Slight file differences

**Review by quuu — COMMENTED** [review]
Reference to 
`stopIcon.png` inside of a Downloads folder?

Needed?

**Comment by BQZic** [comment]
> Reference to
> `stopIcon.png` inside of a Downloads folder?
> 
> Needed?

Should I delete the images folder

**Comment by quuu** [comment]
> > Reference to
> > `stopIcon.png` inside of a Downloads folder?
> > Needed?
> 
> Should I delete the images folder


Yes please, then it should be all good

**Review by quuu — COMMENTED** [review]
Looks good

Coloring is spot on

**Review by quuu — APPROVED** [review]

**Pull request merged**
